# Permalinks
permalink:           pretty

# Setup
title:               alcesleo
tagline:             Yet another dev blog
url:                 https://alcesleo.github.io/
paginate:            5
baseurl:             "http://alcesleo.github.io"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jimmy BÃ¶rjesson
  url:               https://github.com/alcesleo
  email:             alcesleo@gmail.com

# Custom vars
github:
  repo:              https://github.com/alcesleo/alcesleo.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
